### ISSUE TITLE
:o

### ISSUE THREAD

**Issue by chynu** [TrevorEdwards/TrevorEdwards.github.io#1]
![image](https://user-images.githubusercontent.com/13556792/47124364-6e514480-d24b-11e8-98ca-043e8ee5c92d.png)

ic: @chelsea0282

**Comment by chelsea0282** [comment]
yam

**Comment by TrevorEdwards** [comment]
Irrelevant and unforgivable

**Comment by chynu** [comment]
![](https://user-images.githubusercontent.com/13556792/47124364-6e514480-d24b-11e8-98ca-043e8ee5c92d.png)
